# Generated by Django 5.1.3 on 2024-11-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MartialArt',
            fields=[
                ('martial_art_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tutorial', models.TextField()),
                ('reference_file', models.FileField(upload_to='movement_references/')),
                ('martial_art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.martialart')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('movement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='api.movement')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_score', models.FloatField()),
                ('movement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_histories', to='api.movement')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_histories', to='api.practicesession')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_histories', to='api.user')),
            ],
        ),
        #migrations.RenameField(
        #    model_name='martialart',
        #    old_name='id',
        #    new_name='martial_art_id',
        #),
        # migrations.RenameField(
        #    model_name='movement',
        #    old_name='id',
        #    new_name='movement_id',
        #),
        # migrations.RenameField(
        #    model_name='practicesession',
        #    old_name='id',
        #    new_name='session_id',
        #),
        # migrations.RenameField(
        #    model_name='progresshistory',
        #    old_name='id',
        #    new_name='history_id',
        #),
        #    migrations.RenameField(
        #    model_name='user',
        #    old_name='id',
        #    new_name='user_id',
        #),
        
        
           
    ]
 